CREATE DATABASE metastore_db;
CREATE ROLE hive WITH SUPERUSER CREATEDB CREATEROLE LOGIN PASSWORD 'hive';
GRANT ALL PRIVILEGES ON DATABASE metastore_db TO hive;
GRANT ALL ON SCHEMA public TO hive;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO hive;

CREATE DATABASE airflow_db;
CREATE ROLE airflow WITH SUPERUSER CREATEDB CREATEROLE LOGIN PASSWORD 'airflow';
GRANT ALL PRIVILEGES ON DATABASE airflow_db TO airflow;
GRANT ALL ON SCHEMA public TO airflow;